### ISSUE TITLE
Pymongo & Flask

### ISSUE THREAD

**Issue by ghost** [JettChenT/SSBS-PC#9]
![image](https://user-images.githubusercontent.com/47623453/59080690-ac0af680-891c-11e9-9350-da6524d92fe3.png)
There is a problem with the website.
I ran it locally and got the following error:
```
Traceback (most recent call last):
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/pymongo/uri_parser.py", line 254, in _get_dns_srv_hosts
    results = resolver.query('_mongodb._tcp.' + hostname, 'SRV')
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/dns/resolver.py", line 1102, in query
    lifetime)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/dns/resolver.py", line 1002, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: _mongodb._tcp.cluster0-869xj.mongodb.net., _mongodb._tcp.cluster0-869xj.mongodb.net.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 779, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 300, in __init__
    self._load_unlocked()
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 324, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 386, in load_app
    raise_if_not_found=False)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/flask/cli.py", line 236, in locate_app
    __import__(module_name)
  File "/Users/--------/SSBS-PC/app.py", line 6, in <module>
    "mongodb+srv://admin:JettChen@cluster0-869xj.mongodb.net/test?retryWrites=true")
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/pymongo/mongo_client.py", line 524, in __init__
    res = uri_parser.parse_uri(entity, port, warn=True)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/pymongo/uri_parser.py", line 366, in parse_uri
    nodes = _get_dns_srv_hosts(fqdn)
  File "/Users/--------/.local/share/virtualenvs/SSBS-PC-pTxL1ZXg/lib/python3.7/site-packages/pymongo/uri_parser.py", line 256, in _get_dns_srv_hosts
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: None of DNS query names exist: _mongodb._tcp.cluster0-869xj.mongodb.net., _mongodb._tcp.cluster0-869xj.mongodb.net.
```
I ran it with Pipenv installation, it should return similar errors.

I presume something's wrong with your MongoDB configuration. Deleted the database, perhaps?

Also update your Flask to 1.0.3 at #6.

**Comment by ghost** [comment]
@JettChenT This is emergency :sos:

**Comment by ghost** [comment]
@JettChenT Also look at Pull Request #10, improvements!

**Comment by ghost** [comment]
Never mind, I see you've deleted your MongoDB database :-1:
